[windows]
AQA-REG03.unimedara.com.br
AQA-ATD10.unimedara.com.br
AQA-CMD02.unimedara.com.br
AQA-CAD03.unimedara.com.br
AQA-NAP26.unimedara.com.br
AQA-NAP10.unimedara.com.br
AQA-FIN10.unimedara.com.br
AQA-ATD08.unimedara.com.br
AQA-UNV08.unimedara.com.br
AQA-NAP30.unimedara.com.br
AQA-NAP15.unimedara.com.br
AQA-UNV11.unimedara.com.br
AQA-NAP05.unimedara.com.br
AQA-NAP24.unimedara.com.br
AQA-UNV31.unimedara.com.br
AQA-CMD16.unimedara.com.br
AQA-NAP33.unimedara.com.br
AQA-CMD04.unimedara.com.br
AQA-NAP07.unimedara.com.br
AQA-CMD07.unimedara.com.br
AQA-CAD05.unimedara.com.br
AQA-NAP34.unimedara.com.br
AQA-CTB01.unimedara.com.br
AQA-NAP22.unimedara.com.br
AQA-FIN03.unimedara.com.br
AQA-ATD07.unimedara.com.br
AQA-UNV48.unimedara.com.br
AQA-LAB02.unimedara.com.br
AQA-INT06.unimedara.com.br
AQA-CMD01.unimedara.com.br
AQA-RCO01.unimedara.com.br
AQA-JUR04.unimedara.com.br
AQA-UNV13.unimedara.com.br
AQA-CMD03.unimedara.com.br
AQA-UNV14.unimedara.com.br
AQA-NAP01.unimedara.com.br
AQA-UNV01.unimedara.com.br
AQA-NAP06.unimedara.com.br
AQA-AGT01.unimedara.com.br
AQA-UNV44.unimedara.com.br
AQA-INT03.unimedara.com.br
AQA-ATD06.unimedara.com.br
AQA-AGT05.unimedara.com.br
AQA-INT02.unimedara.com.br
AQA-ATD03.unimedara.com.br
AQA-ATD05.unimedara.com.br
AQA-INT05.unimedara.com.br
AQA-ATD02.unimedara.com.br
AQA-CAD01.unimedara.com.br
AQA-NAP27.unimedara.com.br
AQA-SAC02.unimedara.com.br
AQA-CAD06.unimedara.com.br
AQA-LAB01.unimedara.com.br
AQA-INT04.unimedara.com.br
AQA-NAP31.unimedara.com.br
AQA-MKT01.unimedara.com.br
AQA-AGT04.unimedara.com.br
AQA-NAP20.unimedara.com.br
AQA-UNV05.unimedara.com.br
AQA-JUR01.unimedara.com.br
AQA-SAC01.unimedara.com.br
AQA-ATD12.unimedara.com.br
AQA-LAB11.unimedara.com.br
AQA-NAP23.unimedara.com.br
AQA-UNV37.unimedara.com.br
AQA-CMD06.unimedara.com.br
AQA-MAN01.unimedara.com.br
AQA-REG05.unimedara.com.br
AQA-UNV40.unimedara.com.br
AQA-UNV06.unimedara.com.br
AQA-CMD05.unimedara.com.br
AQA-LAB13.unimedara.com.br
AQA-NAP13.unimedara.com.br
AQA-NAP12.unimedara.com.br
AQA-NAP08.unimedara.com.br
AQA-NAP17.unimedara.com.br
AQA-NAP11.unimedara.com.br
AQA-NAP09.unimedara.com.br
AQA-ATD14.unimedara.com.br
AQA-ATD11.unimedara.com.br
AQA-NAP03.unimedara.com.br
AQA-UNV02.unimedara.com.br
AQA-UNV10.unimedara.com.br
AQA-NAP32.unimedara.com.br
AQA-UNV07.unimedara.com.br
AQA-NAP14.unimedara.com.br
AQA-RHU07.unimedara.com.br
AQA-CAD02.unimedara.com.br
AQA-CAD04.unimedara.com.br
AQA-UNV17.unimedara.com.br
AQA-NAP16.unimedara.com.br
AQA-RHU04.unimedara.com.br
AQA-INT01.unimedara.com.br
AQA-SAC03.unimedara.com.br
AQA-CAD07.unimedara.com.br
AQA-UNV45.unimedara.com.br
AQA-NAP25.unimedara.com.br
AQA-UNV39.unimedara.com.br
AQA-NAP29.unimedara.com.br
AQA-REG04.unimedara.com.br
AQA-LAB04.unimedara.com.br
AQA-NAP18.unimedara.com.br
AQA-UNV04.unimedara.com.br
AQA-UNV47.unimedara.com.br
AQA-REG01.unimedara.com.br
AQA-NAP02.unimedara.com.br
AQA-UNV26.unimedara.com.br
AQA-UNV21.unimedara.com.br
AQA-UNV12.unimedara.com.br
AQA-UNV41.unimedara.com.br
AQA-LAB14.unimedara.com.br
AQA-ATD15.unimedara.com.br
AQA-MKT03.unimedara.com.br
AQA-UNV15.unimedara.com.br
AQA-REG02.unimedara.com.br
AQA-REG07.unimedara.com.br
AQA-DPS01.unimedara.com.br
AQA-BKP01.unimedara.com.br
AQA-TTN03.unimedara.com.br
AQA-UNV09.unimedara.com.br
AQA-FIN01.unimedara.com.br
AQA-ATD09.unimedara.com.br
AQA-ATD13.unimedara.com.br
AQA-CMD17.unimedara.com.br
AQA-INT07.unimedara.com.br
AQA-LAB03.unimedara.com.br
AQA-FIN02.unimedara.com.br
AQA-UNV22.unimedara.com.br
AQA-QLD01.unimedara.com.br
AQA-NAP28.unimedara.com.br
AQA-CMD08.unimedara.com.br
AQA-SAC04.unimedara.com.br
AQA-CMD09.unimedara.com.br
AQA-NAP19.unimedara.com.br
AQA-ATD01.unimedara.com.br
AQA-ATD04.unimedara.com.br
AQA-UNV43.unimedara.com.br
AQA-UNV33.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

