[windows]
HSP-CDI02.unimedara.com.br
HSP-CDI03.unimedara.com.br
HSP-CDI04.unimedara.com.br
HSP-CDI05.unimedara.com.br
HSP-CDI06.unimedara.com.br
HSP-CDI07.unimedara.com.br
HSP-CDI08.unimedara.com.br
HSP-CDI09.unimedara.com.br
HSP-CDI09OLD.unimedara.com.br
HSP-CDI10.unimedara.com.br
HSP-CDI11.unimedara.com.br
HSP-CDI12.unimedara.com.br
HSP-CDI13.unimedara.com.br
HSP-CDI14.unimedara.com.br
HSP-CDI17.unimedara.com.br
HSP-CDI18.unimedara.com.br
HSP-CDI19.unimedara.com.br
HSP-CDI22.unimedara.com.br
HSP-CDI26.unimedara.com.br
HSP-CDI31.unimedara.com.br
HSP-CDI32.unimedara.com.br
HSP-CDI33.unimedara.com.br
HSP-CDI34.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

