[windows]
HSP-CIR01.unimedara.com.br
HSP-CIR01OLD.unimedara.com.br
HSP-CIR02.unimedara.com.br
HSP-CIR03.unimedara.com.br
HSP-CIR04.unimedara.com.br
HSP-CIR05.unimedara.com.br
HSP-CIR06.unimedara.com.br
HSP-CIR07.unimedara.com.br
HSP-CIR09.unimedara.com.br
HSP-CIR11.unimedara.com.br
HSP-CIR12.unimedara.com.br
HSP-CIR13.unimedara.com.br
HSP-CIR14.unimedara.com.br
HSP-CIR14OLD.unimedara.com.br
HSP-CIR15.unimedara.com.br
HSP-CIR16.unimedara.com.br
HSP-CIR17.unimedara.com.br
HSP-CIR19.unimedara.com.br
HSP-CIR20.unimedara.com.br
HSP-CIR21.unimedara.com.br
HSP-CIR22.unimedara.com.br
HSP-CIR23.unimedara.com.br
HSP-CIR24.unimedara.com.br
HSP-CIR25.unimedara.com.br
HSP-CIR26.unimedara.com.br
HSP-CIR27.unimedara.com.br
HSP-CIR28.unimedara.com.br
HSP-CIR31.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

