[windows]
HSP-CMC01.unimedara.com.br
HSP-CMC02.unimedara.com.br
HSP-CMC03.unimedara.com.br
HSP-CMC03OLD.unimedara.com.br
HSP-CMC04.unimedara.com.br
HSP-CMC04OLD.unimedara.com.br
HSP-CMC05.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

