[windows]
HSP-CMT01.unimedara.com.br
HSP-CMT02.unimedara.com.br
HSP-CMT04.unimedara.com.br
HSP-CMT05.unimedara.com.br
HSP-CMT06.unimedara.com.br
HSP-CMT07.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

