[windows]
HSP-CPR01.unimedara.com.br
HSP-CPR01OLD.unimedara.com.br
HSP-CPR02.unimedara.com.br
HSP-CPR02OLD.unimedara.com.br
HSP-CPR03.unimedara.com.br
HSP-CPR04.unimedara.com.br
HSP-CPR05.unimedara.com.br
HSP-CPR06.unimedara.com.br
HSP-CPR07.unimedara.com.br
HSP-CPR08.unimedara.com.br
HSP-CPR09.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

