[windows]
HSP-ENG01.unimedara.com.br
HSP-ENG02.unimedara.com.br
HSP-ENG03.unimedara.com.br
HSP-ENG04.unimedara.com.br
HSP-ENG05.unimedara.com.br
HSP-ENG05OLD.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

