[windows]
HSP-FAT01.unimedara.com.br
HSP-FAT02.unimedara.com.br
HSP-FAT03.unimedara.com.br
HSP-FAT04.unimedara.com.br
HSP-FAT05.unimedara.com.br
HSP-FAT06.unimedara.com.br
HSP-FAT07.unimedara.com.br
HSP-FAT08.unimedara.com.br
HSP-FAT09.unimedara.com.br
HSP-FAT10.unimedara.com.br
HSP-FAT11.unimedara.com.br
HSP-FAT12.unimedara.com.br
HSP-FAT13.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

