[windows]
HSP-HEM01.unimedara.com.br
HSP-HEM02.unimedara.com.br
HSP-HEM03.unimedara.com.br
HSP-HEM04.unimedara.com.br
HSP-HEM05.unimedara.com.br
HSP-HEM06OLD.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

