ini
[windows]

HSP-SPP01.unimedara.com.br
NOTE42.unimedara.com.br
NOTE102.unimedara.com.br
NOTE67.unimedara.com.br
OPE-UNL03.unimedara.com.br
NOTE01.unimedara.com.br
NOTE167.unimedara.com.br
OPE-ATD22.unimedara.com.br
NOTE120.unimedara.com.br
NOTE123.unimedara.com.br
HSP-TTN11OLD.unimedara.com.br
NOTE173.unimedara.com.br
OPE-INF08.unimedara.com.br
AQA-INT05.unimedara.com.br
NOTE183.unimedara.com.br
AQA-UNV09.unimedara.com.br
AQA-LAB14.unimedara.com.br
NOTE118.unimedara.com.br
NOTE43.unimedara.com.br
NOTE91.unimedara.com.br
HSP-REG02.unimedara.com.br
HSP-FAT11.unimedara.com.br
MUE-ATD10.unimedara.com.br
OPE-REG06.unimedara.com.br
NOTE15.unimedara.com.br
OPE-ATD27.unimedara.com.br
NOTE84.unimedara.com.br
HSP-REG07.unimedara.com.br
AQA-SAC01.unimedara.com.br
MUE-ATD07.unimedara.com.br
NOTE108.unimedara.com.br
NOTE127.unimedara.com.br
NOTE62.unimedara.com.br
NOTE133.unimedara.com.br
NOTE194.unimedara.com.br
HSP-CPR01OLD.unimedara.com.br
NOTE124.unimedara.com.br
NOTE07.unimedara.com.br
NOTE37OLD.unimedara.com.br
NOTE39.unimedara.com.br
NOTE65.unimedara.com.br
NOTE33.unimedara.com.br
MUE-ATD02.unimedara.com.br
NOTE186.unimedara.com.br
NOTE11.unimedara.com.br
HSP-ECO05.unimedara.com.br
NOTE70.unimedara.com.br
HSP-SMT01.unimedara.com.br
HSP-BKP01.unimedara.com.br
NOTE100.unimedara.com.br
NOTE24.unimedara.com.br
AQA-UNV04.unimedara.com.br
NOTE153.unimedara.com.br
NOTE136.unimedara.com.br
HSP-UTI05.unimedara.com.br
NOTE125.unimedara.com.br
HSP-NTR07.unimedara.com.br
AQA-INT02.unimedara.com.br
NOTE171.unimedara.com.br
NOTE111.unimedara.com.br
OPE-CMD10.unimedara.com.br
NOTE172.unimedara.com.br
HSP-CCI03.unimedara.com.br
HSP-SMT06.unimedara.com.br
HSP-CCI05.unimedara.com.br
NOTE25.unimedara.com.br
NOTE152.unimedara.com.br
NOTE05.unimedara.com.br
NOTE10.unimedara.com.br
NOTE99.unimedara.com.br
HSP-RHU03.unimedara.com.br
OPE-ADM02.unimedara.com.br
NOTE163.unimedara.com.br
HSP-SMT02.unimedara.com.br
NOTE78.unimedara.com.br
HSP-ALM05.unimedara.com.br
HSP-PRI10.unimedara.com.br
NOTE90.unimedara.com.br
NOTE77.unimedara.com.br
HSP-QUI13.unimedara.com.br
AQA-ATD11.unimedara.com.br
MAT-UNV04.unimedara.com.br
HSP-UEM23.unimedara.com.br
HSP-LAB07.unimedara.com.br
HSP-LAB04.unimedara.com.br
HSP-CIR22.unimedara.com.br
OPE-ATD25.unimedara.com.br
NOTE130.unimedara.com.br
HSP-SDU05.unimedara.com.br
MAT-ATD06.unimedara.com.br
MAT-UNV08.unimedara.com.br
AQA-BKP01.unimedara.com.br
HSP-PPE13.unimedara.com.br
NOTE93.unimedara.com.br
NOTE107.unimedara.com.br
NOTE68.unimedara.com.br
NOTE165.unimedara.com.br
NOTE154.unimedara.com.br
NOTE192.unimedara.com.br
NOTE09.unimedara.com.br
NOTE64.unimedara.com.br
NOTE61.unimedara.com.br
HSP-UEM25.unimedara.com.br
AQA-QLD01.unimedara.com.br
NOTE134.unimedara.com.br
NOTE47.unimedara.com.br
AQA-UNV22NEW.unimedara.com.br
AQA-UNV22.unimedara.com.br
NOTE53.unimedara.com.br
NOTE57.unimedara.com.br
NOTE193.unimedara.com.br
NOTE46.unimedara.com.br
HSP-UEM30.unimedara.com.br
NOTE164.unimedara.com.br
NOTE17.unimedara.com.br
NOTE190.unimedara.com.br
HSP-PRT04OLD.unimedara.com.br
HSP-GDL08.unimedara.com.br
HSP-TTN12.unimedara.com.br
NOTE49.unimedara.com.br
NOTE157.unimedara.com.br
HSP-PRT03OLD.unimedara.com.br
NOTE137.unimedara.com.br
AQA-IN07.unimedara.com.br
HSP-PRT03.unimedara.com.br
HSP-SEG25OLD.unimedara.com.br
HSP-SEG01NEW.unimedara.com.br
HSP-CMC03.unimedara.com.br
MUE-ATD01OLD.unimedara.com.br
AQA-ATD09OLD.unimedara.com.br
HSP-UEM08OLD.unimedara.com.br
HSP-UEM22.unimedara.com.br
HSP-UEM08NEW.unimedara.com.br
MUE-ATD04OLD.unimedara.com.br
MUE-ATD09NEW.unimedara.com.br
HSP-PRT02.unimedara.com.br 

[windows:vars]
ansible_connection=winrm
ansible_port=5985
ansible_winrm_scheme=http
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_user=cscarpa@UNIMEDARA.COM.BR



