ini

[windows]

HSP-ALM01.unimedara.com.br
HSP-ALM02.unimedara.com.br
HSP-ALM03.unimedara.com.br
HSP-ALM04.unimedara.com.br
HSP-ALM05.unimedara.com.br
HSP-ALM05OLD.unimedara.com.br
HSP-ALM06.unimedara.com.br
HSP-ALM07.unimedara.com.br
HSP-ATF01.unimedara.com.br
HSP-ATF02.unimedara.com.br
HSP-ATF03.unimedara.com.br
HSP-ATF04.unimedara.com.br
HSP-BER01.unimedara.com.br
HSP-BER02.unimedara.com.br
HSP-BER04.unimedara.com.br
HSP-BER05.unimedara.com.br
HSP-BKP01.unimedara.com.br
HSP-BKP02.unimedara.com.br
HSP-BKP04.unimedara.com.br
HSP-BKP05.unimedara.com.br
HSP-CCI01.unimedara.com.br
HSP-CCI02.unimedara.com.br
HSP-CCI03.unimedara.com.br
HSP-CCI04.unimedara.com.br
HSP-CCI05.unimedara.com.br
HSP-CCI06.unimedara.com.br
HSP-CDI02.unimedara.com.br
HSP-CDI03.unimedara.com.br
HSP-CDI04.unimedara.com.br
HSP-CDI05.unimedara.com.br
HSP-CDI06.unimedara.com.br
HSP-CDI07.unimedara.com.br
HSP-CDI08.unimedara.com.br
HSP-CDI09.unimedara.com.br
HSP-CDI09OLD.unimedara.com.br
HSP-CDI10.unimedara.com.br
HSP-CDI11.unimedara.com.br
HSP-CDI12.unimedara.com.br
HSP-CDI13.unimedara.com.br
HSP-CDI14.unimedara.com.br
HSP-CDI17.unimedara.com.br
HSP-CDI18.unimedara.com.br
HSP-CDI19.unimedara.com.br
HSP-CDI22.unimedara.com.br
HSP-CDI26.unimedara.com.br
HSP-CDI31.unimedara.com.br
HSP-CDI32.unimedara.com.br
HSP-CDI33.unimedara.com.br
HSP-CDI34.unimedara.com.br
HSP-CIR01.unimedara.com.br
HSP-CIR01OLD.unimedara.com.br
HSP-CIR02.unimedara.com.br
HSP-CIR03.unimedara.com.br
HSP-CIR04.unimedara.com.br
HSP-CIR05.unimedara.com.br
HSP-CIR06.unimedara.com.br
HSP-CIR07.unimedara.com.br
HSP-CIR09.unimedara.com.br
HSP-CIR11.unimedara.com.br
HSP-CIR12.unimedara.com.br
HSP-CIR13.unimedara.com.br
HSP-CIR14.unimedara.com.br
HSP-CIR14OLD.unimedara.com.br
HSP-CIR15.unimedara.com.br
HSP-CIR16.unimedara.com.br
HSP-CIR17.unimedara.com.br
HSP-CIR19.unimedara.com.br
HSP-CIR20.unimedara.com.br
HSP-CIR21.unimedara.com.br
HSP-CIR22.unimedara.com.br
HSP-CIR23.unimedara.com.br
HSP-CIR24.unimedara.com.br
HSP-CIR25.unimedara.com.br
HSP-CIR26.unimedara.com.br
HSP-CIR27.unimedara.com.br
HSP-CIR28.unimedara.com.br
HSP-CIR31.unimedara.com.br
HSP-CMC01.unimedara.com.br
HSP-CMC02.unimedara.com.br
HSP-CMC03.unimedara.com.br
HSP-CMC03OLD.unimedara.com.br
HSP-CMC04.unimedara.com.br
HSP-CMC04OLD.unimedara.com.br
HSP-CMC05.unimedara.com.br
HSP-CMT01.unimedara.com.br
HSP-CMT02.unimedara.com.br
HSP-CMT04.unimedara.com.br
HSP-CMT05.unimedara.com.br
HSP-CMT06.unimedara.com.br
HSP-CMT07.unimedara.com.br
HSP-CPR01.unimedara.com.br
HSP-CPR01OLD.unimedara.com.br
HSP-CPR02.unimedara.com.br
HSP-CPR02OLD.unimedara.com.br
HSP-CPR03.unimedara.com.br
HSP-CPR04.unimedara.com.br
HSP-CPR05.unimedara.com.br
HSP-CPR06.unimedara.com.br
HSP-CPR07.unimedara.com.br
HSP-CPR08.unimedara.com.br
HSP-CPR09.unimedara.com.br
HSP-DPS01.unimedara.com.br
HSP-DPS02.unimedara.com.br
HSP-DPS03.unimedara.com.br
HSP-DPS04.unimedara.com.br
HSP-DPS05.unimedara.com.br
HSP-ECO01.unimedara.com.br
HSP-ECO03.unimedara.com.br
HSP-ECO04.unimedara.com.br
HSP-ECO05.unimedara.com.br
HSP-ECS01.unimedara.com.br
HSP-ECS01OLD.unimedara.com.br
HSP-ECS02.unimedara.com.br
HSP-ECS03.unimedara.com.br
HSP-EFM01.unimedara.com.br
HSP-EFM02.unimedara.com.br
HSP-EFM05.unimedara.com.br
HSP-ENG01.unimedara.com.br
HSP-ENG02.unimedara.com.br
HSP-ENG03.unimedara.com.br
HSP-ENG04.unimedara.com.br
HSP-ENG05.unimedara.com.br
HSP-ENG05OLD.unimedara.com.br
HSP-FAT01.unimedara.com.br
HSP-FAT02.unimedara.com.br
HSP-FAT03.unimedara.com.br
HSP-FAT04.unimedara.com.br
HSP-FAT05.unimedara.com.br
HSP-FAT06.unimedara.com.br
HSP-FAT07.unimedara.com.br
HSP-FAT08.unimedara.com.br
HSP-FAT09.unimedara.com.br
HSP-FAT10.unimedara.com.br
HSP-FAT11.unimedara.com.br
HSP-FAT12.unimedara.com.br
HSP-FAT13.unimedara.com.br
HSP-FIN01.unimedara.com.br
HSP-FIN02.unimedara.com.br
HSP-FON01.unimedara.com.br
HSP-FTA01.unimedara.com.br
HSP-GDL01.unimedara.com.br
HSP-GDL02.unimedara.com.br
HSP-GDL03.unimedara.com.br
HSP-GDL04.unimedara.com.br
HSP-GDL05.unimedara.com.br
HSP-GDL06.unimedara.com.br
HSP-GDL07.unimedara.com.br
HSP-GDL08.unimedara.com.br
HSP-HEM01.unimedara.com.br
HSP-HEM02.unimedara.com.br
HSP-HEM03.unimedara.com.br
HSP-HEM04.unimedara.com.br
HSP-HEM05.unimedara.com.br
HSP-HEM06OLD.unimedara.com.br
HSP-HPB01.unimedara.com.br
HSP-HPB02.unimedara.com.br
HSP-INF02.unimedara.com.br
HSP-INF03.unimedara.com.br
HSP-INF04.unimedara.com.br
HSP-INF05.unimedara.com.br
HSP-INF06.unimedara.com.br
HSP-INF07.unimedara.com.br
HSP-INF08.unimedara.com.br
HSP-INF09.unimedara.com.br
HSP-INF10.unimedara.com.br
HSP-INF11.unimedara.com.br
HSP-INF12NEW.unimedara.com.br
HSP-INF13.unimedara.com.br
HSP-INF14.unimedara.com.br
HSP-INF15.unimedara.com.br
HSP-INF16.unimedara.com.br
HSP-INF17.unimedara.com.br
HSP-INT01.unimedara.com.br
HSP-INT02.unimedara.com.br
HSP-INT03.unimedara.com.br
HSP-INT04.unimedara.com.br
HSP-INT05.unimedara.com.br
HSP-LAB01.unimedara.com.br
HSP-LAB02.unimedara.com.br
HSP-LAB03.unimedara.com.br
HSP-LAB04.unimedara.com.br
HSP-LAB05.unimedara.com.br
HSP-LAB06.unimedara.com.br
HSP-LAB07.unimedara.com.br
HSP-LAB08.unimedara.com.br
HSP-LAB09.unimedara.com.br
HSP-LAB10.unimedara.com.br
HSP-LAB12.unimedara.com.br
HSP-LAB13.unimedara.com.br
HSP-LAB14.unimedara.com.br
HSP-LAB15.unimedara.com.br
HSP-LAB16.unimedara.com.br
HSP-MAN01.unimedara.com.br
HSP-MES01.unimedara.com.br
HSP-MES02.unimedara.com.br
HSP-MES03.unimedara.com.br
HSP-MES04.unimedara.com.br
HSP-MES04OLD.unimedara.com.br
HSP-NEO01.unimedara.com.br
HSP-NEO02.unimedara.com.br
HSP-NEO04.unimedara.com.br
HSP-NEO05.unimedara.com.br
HSP-NEO06.unimedara.com.br
HSP-NEO07.unimedara.com.br
HSP-NEO08.unimedara.com.br
HSP-NEO08OLD.unimedara.com.br
HSP-NSP01.unimedara.com.br
HSP-NSP02.unimedara.com.br
HSP-NTR01.unimedara.com.br
HSP-NTR02.unimedara.com.br
HSP-NTR03.unimedara.com.br
HSP-NTR04.unimedara.com.br
HSP-NTR05.unimedara.com.br
HSP-NTR06.unimedara.com.br
HSP-NTR07.unimedara.com.br
HSP-PAP04.unimedara.com.br
HSP-PAP07.unimedara.com.br
HSP-PAP08.unimedara.com.br
HSP-PBX01.unimedara.com.br
HSP-PPE01.unimedara.com.br
HSP-PPE02.unimedara.com.br
HSP-PPE03.unimedara.com.br
HSP-PPE04.unimedara.com.br
HSP-PPE05.unimedara.com.br
HSP-PPE06.unimedara.com.br
HSP-PPE07.unimedara.com.br
HSP-PPE08.unimedara.com.br
HSP-PPE09.unimedara.com.br
HSP-PPE10.unimedara.com.br
HSP-PPE11.unimedara.com.br
HSP-PPE12.unimedara.com.br
HSP-PRI01.unimedara.com.br
HSP-PRI02.unimedara.com.br
HSP-PRI03.unimedara.com.br
HSP-PRI04.unimedara.com.br
HSP-PRI05.unimedara.com.br
HSP-PRI06.unimedara.com.br
HSP-PRI07.unimedara.com.br
HSP-PRI08.unimedara.com.br
HSP-PRI10.unimedara.com.br
HSP-PRI11.unimedara.com.br
HSP-PRI12.unimedara.com.br
HSP-PRI14.unimedara.com.br
HSP-PRI15.unimedara.com.br
HSP-PRI16.unimedara.com.br
HSP-PRT01.unimedara.com.br
HSP-PRT02.unimedara.com.br
HSP-PRT03.unimedara.com.br
HSP-PRT03OLD.unimedara.com.br
HSP-PRT04.unimedara.com.br
HSP-PRT04OLD.unimedara.com.br
HSP-PSI01.unimedara.com.br
HSP-PSI02.unimedara.com.br
HSP-QUI01.unimedara.com.br
HSP-QUI02.unimedara.com.br
HSP-QUI03.unimedara.com.br
HSP-QUI04.unimedara.com.br
HSP-QUI04OLD.unimedara.com.br
HSP-QUI05.unimedara.com.br
HSP-QUI06.unimedara.com.br
HSP-QUI07.unimedara.com.br
HSP-QUI08.unimedara.com.br
HSP-QUI09.unimedara.com.br
HSP-QUI12.unimedara.com.br
HSP-QUI13.unimedara.com.br
HSP-RCP01.unimedara.com.br
HSP-RCP02.unimedara.com.br
HSP-RCP03.unimedara.com.br
HSP-RCP04.unimedara.com.br
HSP-RCP05.unimedara.com.br
HSP-RCP07.unimedara.com.br
HSP-REG01.unimedara.com.br
HSP-REG02.unimedara.com.br
HSP-REG04.unimedara.com.br
HSP-REG06.unimedara.com.br
HSP-REG07.unimedara.com.br
HSP-REG08.unimedara.com.br
HSP-REG09.unimedara.com.br
hsp-reg10.unimedara.com.br
HSP-RHU01.unimedara.com.br
HSP-RHU02.unimedara.com.br
HSP-RHU03.unimedara.com.br
HSP-RHU04.unimedara.com.br
HSP-RHU05.unimedara.com.br
HSP-RHU06.unimedara.com.br
HSP-RHU07.unimedara.com.br
HSP-SAM01.unimedara.com.br
HSP-SAM02.unimedara.com.br
HSP-SDU01.unimedara.com.br
HSP-SDU02.unimedara.com.br
HSP-SDU03.unimedara.com.br
HSP-SDU04.unimedara.com.br
HSP-SDU05.unimedara.com.br
HSP-SDU07.unimedara.com.br
HSP-SDU08.unimedara.com.br
HSP-SDU09.unimedara.com.br
HSP-SDU10.unimedara.com.br
HSP-SDU11.unimedara.com.br
HSP-SDU12.unimedara.com.br
HSP-SDU13.unimedara.com.br
HSP-SDU14.unimedara.com.br
HSP-SEC01.unimedara.com.br
HSP-SEC02.unimedara.com.br
HSP-SEC03.unimedara.com.br
HSP-SEG01.unimedara.com.br
HSP-SEG02.unimedara.com.br
HSP-SEG03.unimedara.com.br
HSP-SEG04.unimedara.com.br
HSP-SEG06.unimedara.com.br
HSP-SEG07.unimedara.com.br
HSP-SEG10.unimedara.com.br
HSP-SEG11.unimedara.com.br
HSP-SEG12.unimedara.com.br
HSP-SEG13.unimedara.com.br
HSP-SEG14.unimedara.com.br
HSP-SEG15.unimedara.com.br
HSP-SEG18.unimedara.com.br
HSP-SEG19.unimedara.com.br
HSP-SEG20.unimedara.com.br
HSP-SEG22.unimedara.com.br
HSP-SEG23.unimedara.com.br
HSP-SEG24.unimedara.com.br
HSP-SEG25.unimedara.com.br
HSP-SEG26.unimedara.com.br
HSP-SEG27.unimedara.com.br
HSP-SEG28.unimedara.com.br
HSP-SEG29.unimedara.com.br
HSP-SEG31.unimedara.com.br
HSP-SMT01.unimedara.com.br
HSP-SMT02.unimedara.com.br
HSP-SMT03.unimedara.com.br
HSP-SMT04.unimedara.com.br
HSP-SMT05.unimedara.com.br
HSP-SMT06.unimedara.com.br
HSP-SMT07.unimedara.com.br
HSP-SMT08.unimedara.com.br
HSP-SMT09.unimedara.com.br
HSP-SMT10.unimedara.com.br
HSP-SMT11.unimedara.com.br
HSP-SPP01.unimedara.com.br
HSP-SPP02.unimedara.com.br
HSP-SSO01.unimedara.com.br
HSP-SSO02.unimedara.com.br
HSP-SSO03.unimedara.com.br
HSP-TER01.unimedara.com.br
HSP-TER02.unimedara.com.br
HSP-TER03.unimedara.com.br
HSP-TRR01.unimedara.com.br
HSP-TRR02.unimedara.com.br
HSP-TRR03.unimedara.com.br
HSP-TRR03OLD.unimedara.com.br
HSP-TRR04.unimedara.com.br
HSP-TRR05.unimedara.com.br
HSP-TRR07.unimedara.com.br
HSP-TRR07OLD.unimedara.com.br
HSP-TRR08.unimedara.com.br
HSP-TRR09.unimedara.com.br
HSP-TRR10.unimedara.com.br
HSP-TRR11.unimedara.com.br
HSP-TTN01.unimedara.com.br
HSP-TTN02.unimedara.com.br
HSP-TTN03.unimedara.com.br
HSP-TTN04.unimedara.com.br
HSP-TTN06.unimedara.com.br
HSP-TTN06OLD.unimedara.com.br
HSP-TTN07.unimedara.com.br
HSP-TTN08.unimedara.com.br
HSP-TTN09.unimedara.com.br
HSP-TTN10.unimedara.com.br
HSP-TTN11.unimedara.com.br
HSP-TTN11OLD.unimedara.com.br
HSP-TTN12.unimedara.com.br
HSP-TTN13.unimedara.com.br
HSP-TTN14.unimedara.com.br
HSP-UEM01.unimedara.com.br
HSP-UEM02.unimedara.com.br
HSP-UEM03.unimedara.com.br
HSP-UEM04.unimedara.com.br
HSP-UEM05.unimedara.com.br
HSP-UEM07.unimedara.com.br
HSP-UEM08.unimedara.com.br
HSP-UEM08OLD.unimedara.com.br
HSP-UEM09.unimedara.com.br
HSP-UEM10.unimedara.com.br
HSP-UEM11.unimedara.com.br
HSP-UEM12.unimedara.com.br
HSP-UEM13.unimedara.com.br
HSP-UEM14.unimedara.com.br
HSP-UEM15.unimedara.com.br
HSP-UEM16.unimedara.com.br
HSP-UEM17.unimedara.com.br
HSP-UEM18.unimedara.com.br
HSP-UEM19.unimedara.com.br
HSP-UEM20.unimedara.com.br
HSP-UEM21.unimedara.com.br
HSP-UEM22.unimedara.com.br
HSP-UEM23.unimedara.com.br
HSP-UEM24.unimedara.com.br
HSP-UEM25.unimedara.com.br
HSP-UEM28.unimedara.com.br
HSP-UEM29.unimedara.com.br
HSP-UEM30.unimedara.com.br
HSP-UEM31.unimedara.com.br
HSP-UEM32.unimedara.com.br
HSP-UTI01.unimedara.com.br
HSP-UTI02.unimedara.com.br
HSP-UTI03.unimedara.com.br
HSP-UTI04.unimedara.com.br
HSP-UTI05.unimedara.com.br
HSP-UTI06.unimedara.com.br
HSP-UTI07.unimedara.com.br
HSP-UTI10.unimedara.com.br
HSP-UTI11.unimedara.com.br
HSP-UTI12.unimedara.com.br
HSP-UTI13.unimedara.com.br
HSP-UTI14.unimedara.com.br
HSP-UTI15.unimedara.com.br
HSP-UTI16.unimedara.com.br
HSP-UTI19.unimedara.com.br
HSP-UTI20.unimedara.com.br
HSP-UTI21.unimedara.com.br
HSP-UTI22.unimedara.com.br
HSP-UTI23.unimedara.com.br


[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985