ini

[windows]

HSP-SEG24.unimedara.com.br
HSP-SEG25OLD.unimedara.com.br
HSP-SEG04.unimedara.com.br
HSP-SEG23.unimedara.com.br
HSP-SEG15.unimedara.com.br
HSP-SEG20.unimedara.com.br
HSP-SEG06.unimedara.com.br
HSP-SEG11.unimedara.com.br
HSP-SEG07.unimedara.com.br
HSP-SEG14.unimedara.com.br
HSP-SEG28.unimedara.com.br
HSP-SEG02.unimedara.com.br
HSP-SEG03.unimedara.com.br
HSP-SEG26.unimedara.com.br
HSP-SEG31.unimedara.com.br
HSP-SEG27.unimedara.com.br
HSP-SEG29.unimedara.com.br
HSP-SEG12.unimedara.com.br
HSP-SEG18.unimedara.com.br
HSP-SEG19.unimedara.com.br
HSP-SEG22.unimedara.com.br
HSP-SEG10.unimedara.com.br
HSP-SEG13.unimedara.com.br
HSP-SEG01.unimedara.com.br
HSP-SEG25.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

