[windows]
HSP-INF02.unimedara.com.br
HSP-INF03.unimedara.com.br
HSP-INF04.unimedara.com.br
HSP-INF05.unimedara.com.br
HSP-INF06.unimedara.com.br
HSP-INF07.unimedara.com.br
HSP-INF08.unimedara.com.br
HSP-INF09.unimedara.com.br
HSP-INF10.unimedara.com.br
HSP-INF11.unimedara.com.br
HSP-INF12NEW.unimedara.com.br
HSP-INF13.unimedara.com.br
HSP-INF14.unimedara.com.br
HSP-INF15.unimedara.com.br
HSP-INF16.unimedara.com.br
HSP-INF17.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

