[windows]
HSP-LAB01.unimedara.com.br
HSP-LAB02.unimedara.com.br
HSP-LAB03.unimedara.com.br
HSP-LAB04.unimedara.com.br
HSP-LAB05.unimedara.com.br
HSP-LAB06.unimedara.com.br
HSP-LAB07.unimedara.com.br
HSP-LAB08.unimedara.com.br
HSP-LAB09.unimedara.com.br
HSP-LAB10.unimedara.com.br
HSP-LAB12.unimedara.com.br
HSP-LAB13.unimedara.com.br
HSP-LAB14.unimedara.com.br
HSP-LAB15.unimedara.com.br
HSP-LAB16.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

