[windows]

OPE-ADM01.unimedara.com.br
OPE-ADM02.unimedara.com.br
OPE-ATD01.unimedara.com.br
OPE-ATD02.unimedara.com.br
OPE-ATD03.unimedara.com.br
OPE-ATD04.unimedara.com.br
OPE-ATD06.unimedara.com.br
OPE-ATD08.unimedara.com.br
OPE-ATD09.unimedara.com.br
OPE-ATD11.unimedara.com.br
OPE-ATD12.unimedara.com.br
OPE-ATD14.unimedara.com.br
OPE-ATD16.unimedara.com.br
OPE-ATD18.unimedara.com.br
OPE-ATD22.unimedara.com.br
OPE-ATD24.unimedara.com.br
OPE-ATD25.unimedara.com.br
OPE-ATD26.unimedara.com.br
OPE-ATD27.unimedara.com.br
OPE-ATD28.unimedara.com.br
OPE-ATD29.unimedara.com.br
OPE-ATD30.unimedara.com.br
OPE-ATD31.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
