[windows]

OPE-CMD02.unimedara.com.br
OPE-CMD03.unimedara.com.br
OPE-CMD05.unimedara.com.br
OPE-CMD08.unimedara.com.br
OPE-CMD09.unimedara.com.br
OPE-CMD10.unimedara.com.br
OPE-CMD11.unimedara.com.br
OPE-CMD12.unimedara.com.br
ope-cmd17.unimedara.com.br
OPE-CMD24.unimedara.com.br
OPE-CMD25.unimedara.com.br
OPE-CTB01.unimedara.com.br
OPE-CTB02.unimedara.com.br
OPE-CTB04.unimedara.com.br
OPE-DIR01.unimedara.com.br
OPE-DIR02.unimedara.com.br
OPE-DIR03.unimedara.com.br
OPE-DIR04.unimedara.com.br
OPE-DPS01.unimedara.com.br
OPE-FIN01.unimedara.com.br
OPE-FIN05.unimedara.com.br
OPE-FIN07.unimedara.com.br
OPE-FIN09.unimedara.com.br
OPE-INF01.unimedara.com.br
OPE-INF03.unimedara.com.br
OPE-INF06.unimedara.com.br
OPE-INF07.unimedara.com.br
OPE-INF08.unimedara.com.br
OPE-INF09.unimedara.com.br
OPE-INF10.unimedara.com.br
OPE-INF11.unimedara.com.br
OPE-INF12.unimedara.com.br
OPE-INF13.unimedara.com.br
OPE-INT02.unimedara.com.br
OPE-INT04.unimedara.com.br
OPE-INT15.unimedara.com.br
OPE-MKT02.unimedara.com.br
OPE-RCO03.unimedara.com.br
OPE-RCO04.unimedara.com.br
OPE-REG01.unimedara.com.br
OPE-REG03.unimedara.com.br
OPE-REG05.unimedara.com.br
OPE-REG06.unimedara.com.br
OPE-REG07.unimedara.com.br
OPE-REG08.unimedara.com.br
OPE-REG10.unimedara.com.br
OPE-REG11.unimedara.com.br
OPE-RRA01.unimedara.com.br
OPE-RRA02.unimedara.com.br
OPE-RRA03.unimedara.com.br
OPE-RRA04.unimedara.com.br
OPE-RRA05.unimedara.com.br
OPE-RRA06.unimedara.com.br
OPE-SEC01.unimedara.com.br
OPE-SEC02.unimedara.com.br
OPE-TTN01.unimedara.com.br
OPE-TTN02.unimedara.com.br
OPE-TTN04.unimedara.com.br
OPE-TTN05.unimedara.com.br
OPE-UNL03.unimedara.com.br
OPE-VEN02.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

