[windows]
HSP-QUI01.unimedara.com.br
HSP-QUI02.unimedara.com.br
HSP-QUI03.unimedara.com.br
HSP-QUI04.unimedara.com.br
HSP-QUI04OLD.unimedara.com.br
HSP-QUI05.unimedara.com.br
HSP-QUI06.unimedara.com.br
HSP-QUI07.unimedara.com.br
HSP-QUI08.unimedara.com.br
HSP-QUI09.unimedara.com.br
HSP-QUI12.unimedara.com.br
HSP-QUI13.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

