[windows]
HSP-RCP01.unimedara.com.br
HSP-RCP02.unimedara.com.br
HSP-RCP03.unimedara.com.br
HSP-RCP04.unimedara.com.br
HSP-RCP05.unimedara.com.br
HSP-RCP07.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

