[windows]
HSP-REG01.unimedara.com.br
HSP-REG02.unimedara.com.br
HSP-REG04.unimedara.com.br
HSP-REG06.unimedara.com.br
HSP-REG07.unimedara.com.br
HSP-REG08.unimedara.com.br
HSP-REG09.unimedara.com.br
hsp-reg10.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

