[windows]
HSP-SDU01.unimedara.com.br
HSP-SDU02.unimedara.com.br
HSP-SDU03.unimedara.com.br
HSP-SDU04.unimedara.com.br
HSP-SDU05.unimedara.com.br
HSP-SDU07.unimedara.com.br
HSP-SDU08.unimedara.com.br
HSP-SDU09.unimedara.com.br
HSP-SDU10.unimedara.com.br
HSP-SDU11.unimedara.com.br
HSP-SDU12.unimedara.com.br
HSP-SDU13.unimedara.com.br
HSP-SDU14.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

