[windows]
HSP-SMT01.unimedara.com.br
HSP-SMT02.unimedara.com.br
HSP-SMT03.unimedara.com.br
HSP-SMT04.unimedara.com.br
HSP-SMT05.unimedara.com.br
HSP-SMT06.unimedara.com.br
HSP-SMT07.unimedara.com.br
HSP-SMT08.unimedara.com.br
HSP-SMT09.unimedara.com.br
HSP-SMT10.unimedara.com.br
HSP-SMT11.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

