[windows]
HSP-TRR01.unimedara.com.br
HSP-TRR02.unimedara.com.br
HSP-TRR03.unimedara.com.br
HSP-TRR03OLD.unimedara.com.br
HSP-TRR04.unimedara.com.br
HSP-TRR05.unimedara.com.br
HSP-TRR07.unimedara.com.br
HSP-TRR07OLD.unimedara.com.br
HSP-TRR08.unimedara.com.br
HSP-TRR09.unimedara.com.br
HSP-TRR10.unimedara.com.br
HSP-TRR11.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

