[windows]
HSP-TTN01.unimedara.com.br
HSP-TTN02.unimedara.com.br
HSP-TTN03.unimedara.com.br
HSP-TTN04.unimedara.com.br
HSP-TTN06.unimedara.com.br
HSP-TTN06OLD.unimedara.com.br
HSP-TTN07.unimedara.com.br
HSP-TTN08.unimedara.com.br
HSP-TTN09.unimedara.com.br
HSP-TTN10.unimedara.com.br
HSP-TTN11.unimedara.com.br
HSP-TTN11OLD.unimedara.com.br
HSP-TTN12.unimedara.com.br
HSP-TTN13.unimedara.com.br
HSP-TTN14.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

