[windows]
HSP-UEM01.unimedara.com.br
HSP-UEM02.unimedara.com.br
HSP-UEM03.unimedara.com.br
HSP-UEM04.unimedara.com.br
HSP-UEM05.unimedara.com.br
HSP-UEM07.unimedara.com.br
HSP-UEM08.unimedara.com.br
HSP-UEM08OLD.unimedara.com.br
HSP-UEM09.unimedara.com.br
HSP-UEM10.unimedara.com.br
HSP-UEM11.unimedara.com.br
HSP-UEM12.unimedara.com.br
HSP-UEM13.unimedara.com.br
HSP-UEM14.unimedara.com.br
HSP-UEM15.unimedara.com.br
HSP-UEM16.unimedara.com.br
HSP-UEM17.unimedara.com.br
HSP-UEM18.unimedara.com.br
HSP-UEM19.unimedara.com.br
HSP-UEM20.unimedara.com.br
HSP-UEM21.unimedara.com.br
HSP-UEM22.unimedara.com.br
HSP-UEM23.unimedara.com.br
HSP-UEM24.unimedara.com.br
HSP-UEM25.unimedara.com.br
HSP-UEM28.unimedara.com.br
HSP-UEM29.unimedara.com.br
HSP-UEM30.unimedara.com.br
HSP-UEM31.unimedara.com.br
HSP-UEM32.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

