[windows]
HSP-UTI01.unimedara.com.br
HSP-UTI02.unimedara.com.br
HSP-UTI03.unimedara.com.br
HSP-UTI04.unimedara.com.br
HSP-UTI05.unimedara.com.br
HSP-UTI06.unimedara.com.br
HSP-UTI07.unimedara.com.br
HSP-UTI10.unimedara.com.br
HSP-UTI11.unimedara.com.br
HSP-UTI12.unimedara.com.br
HSP-UTI13.unimedara.com.br
HSP-UTI14.unimedara.com.br
HSP-UTI15.unimedara.com.br
HSP-UTI16.unimedara.com.br
HSP-UTI19.unimedara.com.br
HSP-UTI20.unimedara.com.br
HSP-UTI21.unimedara.com.br
HSP-UTI22.unimedara.com.br
HSP-UTI23.unimedara.com.br

[windows:vars]
ansible_user=cscarpa@UNIMEDARA.COM.BR
ansible_connection=winrm
ansible_winrm_transport=kerberos
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

