---
- name: Remover executáveis e atalhos antigos do Tasy
  hosts: windows
  gather_facts: no

  vars:
    caminhos_busca:
      - "C:\\Users"
      - "C:\\Users\\Public"
      - "C:\\Users\\Public\\Desktop"
      - "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs"

    padroes_tasy:
      - "*tasy*.exe"
      - "*tasy*.lnk"
      - "*tasy*.jnlp"
      - "*Tasy*.exe"
      - "*Tasy*.lnk"
      - "*Tasy*.jnlp"
      - "TasyRel - Atalho.exe"
      - "tasy java.lnk"
      - "tasy java.jnlp"
      - "tasy java - atalho.jnlp"
      - "tasy - atalho.exe"

  roles:
    - limpar_atalho_tasy


