---
- name: Desinstalar McAfee usando GUIDs MSI
  hosts: windows
  gather_facts: no

  roles:
    - role: uninstall_mcafee
      vars:
        mcafee_reboot: false   # true se quiser reiniciar automaticamente

